# Generated by Django 3.2.8 on 2021-10-20 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorModel',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='HospitalModel',
            new_name='Hospital',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Medical Test', 'Medical Test'), ('OPD', 'OPD')], default=django.utils.timezone.now, help_text='Please Select one of them', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='adharno',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
