# Generated by Django 3.2.8 on 2021-10-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_auto_20211020_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Admin', 'Admin')], default='Admin', help_text='Please Select one of them', max_length=30),
        ),
    ]
